name: Update Packagist

on:
  release:
    types: [published]
  push:
    tags:
      - '*'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Update Packagist
        run: |
          curl -XPOST -H'content-type:application/json' \
            "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}" \
            -d'{"repository":{"url":"https://packagist.org/packages/matjeninstudio/laravel-contact-approvable"}}'
